name = "openlinear-mcp"
main = "src/index.ts"
compatibility_date = "2026-05-21"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_server_modules"]
workers_dev = true

[[routes]]
pattern = "mcp.openlinear.tech"
custom_domain = true

[vars]
OPENLINEAR_API_URL = "https://openlinear.tech"
